### ISSUE TITLE
Updates DocBook XSL URL

### ISSUE THREAD

**Issue by der-schmelle2** [tomschr/dbcookbook#27]
## Problem
You are using the URL "http://docbook.sourceforge.net/release/xsl-ns/current/fo/docbook.xsl" in various programlistings. For example in the "Print Customization" chapter: "http://doccookbook.sourceforge.net/html/en/dbc.fo.design-titlepages.html"

## Expected Behaviour
As far as I know this is an old URL to version 1.78.x. From my opinion this should be "https://cdn.docbook.org/release/xsl/current/fo/docbook.xsl", which is 1.79.2 or newer.

**Comment by tomschr** [comment]
Thanks @der-schmelle2 ! Indeed, well spotted! :+1: I've submitted pull request #30 in branch `feature/issue-27`.

**Comment by der-schmelle2** [comment]
Hi tomschr,
great job, but I found 8 additional wrong links in your scripts:
2.3. Writing Customization Layers
3.5. Splitting DocBook Documents
Search for the rest with:
http://docbook.sourceforge.net/release/xsl-ns/current

Thanks!

**Comment by tomschr** [comment]
@der-schmelle2 Thanks for the hints.

I've checked it and I can't find any old DocBook URIs anymore. Maybe you need to distinguish between the page available from SourceForge and the repository. The SF page is not necessarily up-to-date. I update the page from time to time, but that's done manually. You can see the last built time on the main page.

However, my plan is to move the pages completely from SF to GitHub in the future. However, this isn't done yet as it needs some more thoughts (you can find some issues for this topic).

**Comment by der-schmelle2** [comment]
Hi tomschr,
hmm, there are no more wrong links.
Maybe this was a cache "false positive" from the Chromium browser...
I cleared the cache right now and now everything looks fine.

**Comment by tomschr** [comment]
Thanks! I'll close #30
